name: Report a bug
description: Reporting problems with the APP
title: "[Bug]: "
labels: ["bug🐞"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a problem, please complete the title and fill in the following information.
        
        感谢您的反馈，请填写完整标题并填写以下信息。
        
        **Please do not report any issues related to config files.**
        
        **请不要报告与配置文件相关的任何问题。**
        
        This project is a comic reader that allows users write their own config files. And there is no built-in comic source.
        
        本项目是一个漫画阅读器，允许用户编写自己的配置文件，并且没有内置漫画源。
  - type: dropdown
    id: bugType
    attributes:
      label: Bug type
      description: What type of bug are you reporting?
      options:
        - Crash
        - UI
        - Performance
        - Security
        - Reader
        - JS Engine
        - Comic Source
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Describe the problem
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: | 
        App version.
        
        Please try to update if it is not the latest version
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Operating system
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - macOS
        - linux
        - other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: logs
  - type: textarea
    id: screenshotOrVideo
    attributes:
      label: Screenshot or video
      description: Upload relevant screenshots or videos here